# MMC Sdhci pci host controller platform data
obj-$(subst m,y,$(CONFIG_MMC_SDHCI_PCI))				+= platform_sdhci_pci.o
# USB OTG controller platform data
obj-$(subst m,y,$(CONFIG_USB_PENWELL_OTG))				+= platform_usb_otg.o
obj-$(subst m,y,$(CONFIG_USB_DWC3_OTG))        += platform_usb_otg.o
obj-$(subst m,y,$(CONFIG_SND_INTEL_SST))                                += platform_sst_pci.o
